### ISSUE TITLE
Cant Register domain

### ISSUE THREAD

**Issue by myshophosting** [SynergyWholesale/WHMCS-Domains-Module#11]
I tried to register a domain via the new module.. No go.

Logs:

stdClass Object
(
    [status] => ERR_DOMAINREGISTER_FAILED
    [errorMessage] => Domain Register Failed - eppDomainCreate Error - Registry reports - Parameter value syntax error
)

The redacted request:

Array
(
    [nameServers] => Array
        (
            [0] => ns1.myshophosting.com
            [1] => ns2.myshophosting.com
        )

    [years] => 1
    [idProtect] => 
    [specialConditionsAgree] => 1
    [registrant_firstname] => XXXXX
    [registrant_lastname] => XXXXX
    [registrant_address] => Array
        (
            [0] => 17 Swainson St
            [1] => 
        )

    [registrant_suburb] => XXXXX XXXXX
    [registrant_country] => AU
    [registrant_state] => NSW
    [registrant_postcode] => 2304
    [registrant_phone] => +61.XXXXX
    [registrant_email] => XXXXX@gmail.com
    [registrant_organisation] => 
    [eligibility] => {"registrantName":"XXXXX, XXXXX XXXXX","registrantID":"74332736018","registrantIDType":"ABN","eligibilityType":"Sole Trader","eligibilityIDType":"ABN","eligibilityID":"XXXXX, XXXXX XXXXX","eligibilityName":"XXXXX"}
    [php_ver] => 7.3.16
    [whmcs_ver] => 7.10.0-rc.2
    [whmcs_mod_ver] => 2.1.2
    [apiKey] => ****************************************************************
    [resellerID] => *****
    [domainName] => XXXXX.com.au
)

I also tried without a comma in the Registrant name.. same deal.

**Comment by CameronHall** [comment]
Hey @myshophosting,

Sorry for the delay, and thanks for bug reporting!

Did you get this one registered in the end? If not, please submit a ticket via the Synergy Wholesale Management Console and provide the unredacted request whilst referencing this issue :)

Thanks!

**Comment by myshophosting** [comment]
I registered the domain via the Synergy Portal.. Since this report thou I have been able to register other domains. So Im not sure what the issue was.

The other issue reported (domains in pending transfer getting a 'DATA MISSING' error) still exists.

**Comment by CameronHall** [comment]
No worries, I'll close this one for now. 

99% of the time the error you provided is related to an issue with the registrant eligibility data. I recommend you get in touch with our support team the next time it happens :)

**Comment by myshophosting** [comment]
No worries - The weird thing was that I was able to register the domain via the portal with a copy/paste of the same details.

It was the first domain I registered after updating to that new version of the module so figured it was a problem.. But since its been OK!.. All good.
