### ISSUE TITLE
hooks.php

### ISSUE THREAD

**Issue by xyzulu** [SynergyWholesale/WHMCS-Domains-Module#16]
Line 87 is missing a closing " this causes all customer facing pages to be blank. I reported this many hours ago to Synergy, they do not seem to be able to handle bug reports, even this serious there.

**Comment by xyzulu** [comment]
Please see my pull request. I'm not sure how much more I can do to help now.. none of your staff appear to be able to handle the information I provided them in other places

**Comment by CameronHall** [comment]
Thank you for your contribution @xyzulu.
