### ISSUE TITLE
Bug Regession -  Next Due Date

### ISSUE THREAD

**Issue by myshophosting** [SynergyWholesale/WHMCS-Domains-Module#2]
I reported a bug in 2019 which was kindly fixed in version 1.9.15. Unfortunately this bug is back. The sync button now sets the domain Next Due Date to the exact date as the expiry. It should honor the "Sync Next Due Date - Enable - Number of Days to Set Due Date in Advance of Expiry:" setting in the WHMCS Automation settings.

Note: See ticket: SYN-S3315174 (the dropbox video describing the bug is no longer available, but the ticket shows the history etc.)

**Comment by myshophosting** [comment]
Note: See ticket: SYN-S3315174 (the dropbox video describing the bug is no longer available, but the ticket shows the history etc.

**Comment by CameronHall** [comment]
Hi @myshophosting,

Thank you for reporting. I've created a pre-release version of the module [v2.0.2](https://github.com/SynergyWholesale/WHMCS-Domains-Module/releases/tag/v2.0.2) can you please test this and let us know how you go?

Thanks :)

**Comment by myshophosting** [comment]
Thanks - I can confirm the SYNC button now correctly honors the Sync Next Due Date setting.

**Comment by CameronHall** [comment]
Perfect. Thank you :)
