### ISSUE TITLE
Contacts not updating from WHMCS

### ISSUE THREAD

**Issue by myshophosting** [SynergyWholesale/WHMCS-Domains-Module#21]
I have attempted to update the Tech contacts on a few au domains from WHMCS. (admin side). The changes appear to be successful (I get the green confirmation from WHMCS) - but if I check the domain from within Synergy the tech details have not changed. 
This may affect other contacts as well.

**Comment by Luke-McMahon** [comment]
Thanks @myshophosting - we've confirmed the bug and we'll fix it in the next release!
