### ISSUE TITLE
Feature Request: Sync .com.au registrant details

### ISSUE THREAD

**Issue by xyzulu** [SynergyWholesale/WHMCS-Domains-Module#23]
Currently this module only syncs the contacts and expiry date etc, not the Australian Registrant details. This doesn't happen via the cron or the manual option pressing the sync button. This would be a useful feature to add. 
At the moment, domain owners need to do a remote WHOIS to be sure of the current company/ABN etc listed on the domain, the information listed in WHM is only from the initial purchase or transfer.

**Comment by myshophosting** [comment]
I second this :-)

**Comment by hostmate** [comment]
This is a good idea.
