### ISSUE TITLE
Feature Request: Ability for customers to renew expired .au domains within 30 days after expiry

### ISSUE THREAD

**Issue by hostmate** [SynergyWholesale/WHMCS-Domains-Module#25]
Ability for customers to renew expired .au domains within 30 days after expiry when auto renew disabled and no invoice created prior to expiry.

Currently doesn't appear to be available. Manual invoice creation is necessary by administrators.

**Comment by myshophosting** [comment]
The invoice would have been created well before expiry, and payment would trigger renewal?

**Comment by hostmate** [comment]
We don't set auto renew on by default so no invoice is made unless the customer has enabled auto renew. Have now added  to initial post, "when auto renew disabled and no invoice created prior to expiry".

**Comment by myshophosting** [comment]
Shouldn’t domains auto renew unless requested otherwise? Doing it any other way seems weird.

**Comment by andyrb412** [comment]
Personally I'd prefer them NOT to auto-renew unless I specify.

**Comment by CameronHall** [comment]
Hi @hostmate,

This is entirely possible by configuring the "Grace Period Duration" which can be found in the TLD settings under "Setup > Products/Services > Domain Pricing."
![image](https://user-images.githubusercontent.com/7316093/84961814-9a237c80-b148-11ea-823b-8289aacc8548.png)

It looks WHMCS added some new methods after our initial implementation of the pricing sync.
- setGraceFeeDays
- setGraceFeePrice
- setRedemptionFeeDays

We'll update this issue to request the implementation of the above methods which will resolve this issue for all TLDs.

If there are any questions, please let us know :)
