### ISSUE TITLE
Sync Redemption/Grace Fees not syncing

### ISSUE THREAD

**Issue by davscot** [SynergyWholesale/WHMCS-Domains-Module#26]
Hi,

Please feel free to correct me here however my understanding of "Sync Redemption/Grace Fee" option is that it will sync redemption fees into WHMCS and also apply markup %. 

When I select this "Sync Redemption/Grace Fee" option the "current" value under the TLD redemption column remains the same, is this expected or should it sync the "cost" price + add mark up percentage?

WHMCS admin portal location: Utilities > Registrar TLD Sync = TLD Import & Pricing Sync tool
Synergy Wholesale WHMCS Domains Module v2.1.7
WHMCS version: 7.10.2

**Attached is an image to help explain what I am looking at, note I have blanked out pricing**

Thanks 

David.

![Capture4](https://user-images.githubusercontent.com/54739906/87540303-c815c580-c6e2-11ea-9aef-626a9daea943.PNG)

**Comment by CameronHall** [comment]
Hi @davscot,

Thank you for taking the time to report this issue. As discussed in #25, it was a feature that WHMCS added in _after_ our initial implementation and subsequently isn't supported at the moment.

I'll arrange some time for us to resolve a couple of issues here in the coming days and weeks.

**Comment by davscot** [comment]
@CameronHall 

Thanks Cameron, sorry I didn't see #25 (or read far enough into it). Looking forward to the update in due course.

**Comment by JMOSSAU** [comment]
Updated to v2.1.9 and re-ran the domain sync with Sync Redemption/Grace Fee set to ON, however old prices were not updated to the % set in the sync settings. Old prices that were manually entered remain.
