### ISSUE TITLE
Cant register .digital domains via WHMCS

### ISSUE THREAD

**Issue by myshophosting** [SynergyWholesale/WHMCS-Domains-Module#35]
![whmcsdigitaldomainerror](https://user-images.githubusercontent.com/25734941/91919296-ca6ec600-ed08-11ea-8ecc-b5369fdc17c2.png)
I tried to register a .digital domain today via WHMCS and I get the following API response:

'Domain Register Failed - Domain requires premium acknowledgement'

I was able to successfully register the domain directly via Synergy portal - and could not find anything resembling a premium domain acknowledgement.. the domain registered as normal and I was then able to sync in WHMCS.

**Comment by myshophosting** [comment]
Further to this, I was able to register another .digital domain via WHMCS.

Perhaps the cause was the first domain I attempted to register was only three characters?

**Comment by myshophosting** [comment]
API Response:
Array
(
    [errorMessage] => Domain Register Failed - Domain requires premium acknowledgement
    [status] => ERR_DOMAINREGISTER_FAILED
)

**Comment by CameronHall** [comment]
Hey @myshophosting,

Please check that you have your Synergy Wholesale account and WHMCS module configured with premium domain support. 

https://synergywholesale.com/faq/article/enabling-premium-domain-lookups/
https://synergywholesale.com/faq/article/enabling-premium-domain-lookups-in-whmcs/

If it still doesn't work after following those guides, can you please try logging into the client area and ordering the domain through there?

Let us know how you go :)

**Comment by myshophosting** [comment]
OK, I had my WHOIS provider as WHMCS name spinner, I have now changed to Synergy and have premium domains enabled.
I also had premium domains disabled in the API config in Synergy Portal.

Unfortunately, now the domain is registered, I have no way of testing if it helps.

I now have a problem thou - Using the Synergy WHOIS isn't good for me as I offer other domain types - .ca as an example. These are provided by enom as they are unavailable in Synergy.

If a customer now searches for a .ca domain it always shows as unavailable. Am I able use the ENOM WHOIS - and leave the premium domains enabled in WHMCS and keep the "Show premium domains as available" enabled in Synergy and have it all work?

**Comment by CameronHall** [comment]
> If a customer now searches for a .ca domain it always shows as unavailable. Am I able to use the ENOM WHOIS - and leave the premium domains enabled in WHMCS and keep the "Show premium domains as available" enabled in Synergy and have it all work?

I don't have any experience with doing that, but my gut says no. My concern would be that premium domain prices are returned by the search provider, so your prices might come back incorrectly if ENOM responds with a different price than us (which is likely) and the domains will never register automatically.

If there are TLDs we don't support but you wish to sell, I encourage you to reach out to your account manager and they'll work with you to see how we can best accommodate you.
