### ISSUE TITLE
Domain Options page notice and Addons link when DNS management turned off

### ISSUE THREAD

**Issue by jaywalkertoo** [SynergyWholesale/WHMCS-Domains-Module#37]
When DNS Management is turned off in whmcs, the customer Domain Options page has the notice, "NOTICE: If you wish to utilise DNS Hosting, create email forwarders and use the URL forwarding options please visit the addons menu to activate the required addon first." 

2 things:
1. I dont see an Addon menu link in the left menu for .au domains.
2. The "addons menu" text in the notice text is a link to a page that says, "Addons The following addons are available for your domain(s)...". Should there be any thing else on that page. No addons are listed, are we meant to add them ourselves in the html? I assume any changes we make to the module html will get overwritten on any update. There is no language file either so changing just the notice text isnt a long term solution.

Its been confusing a few customers and Im not sure how to deal with it at this stage. We leave DNS management off by default because if we turn it on by default, most of our customers are hosting customers and far too many people play with the Domain Options settings changing to DNS hosting with a simple form dropbox selection which will automatically change the nameservers to synergy DNS hosting and the customers website and email will go offline and they email in frustration wondering why their website is offline and email is down.

Thanks.

**Comment by Luke-McMahon** [comment]
Hey @jaywalkertoo 

Apologies for such a long delay in getting to this.
We've logged this internally and are currently running a fix through QA.

We'll update you here once we've pushed a fix out.

Cheers!

**Comment by Sn0wCrack** [comment]
Hey @jaywalkertoo 

We've now resolved this issue in our new [v2.2.1 release](https://github.com/SynergyWholesale/WHMCS-Domains-Module/releases/tag/v2.2.1).

Now if you have DNS management and Email Forwarding management disabled on the TLD we will no longer attempt to display the DNS section.

One caveat to this is if DNS management or Email Forwarding management is enabled on the domain directly, then we will still display DNS management options on that page.

**Comment by jaywalkertoo** [comment]
Ok missed these posts.

I guess this is related to the new Issue I created "Blank Domain Options page when DNS Management turned off #58".

A blank page doesnt offer any options for me. Previously at least there was some text which I was replacing using javascript telling customers to contact us if they wanted to have DNS hosting turned on. Now there is no reference for me to access to put some notification text on the page. It worked well telling customers to contact us and they would.

Maybe you could add a language variable so we can add some text if DNS management is turned off. Then remove the language variable if DNS management is turned on. Otherwise just some text saying something like "DNS Management options are turned off", then I can replace that with my notice using javascript.

Thanks.
