### ISSUE TITLE
WHMCS v8 - ID Privacy switch in admin doesn't work

### ISSUE THREAD

**Issue by myshophosting** [SynergyWholesale/WHMCS-Domains-Module#38]
In WHMCS 8, if I enable the Domain Privacy switch and save, the domain privacy feature does not get enabled or disabled in Synergy.

IF I change the privacy option IN synergy and then use the SYNC button in WHMCS, the correct value is synced back to WHMCS.. it's just not set going the other way.

**Comment by xyzulu** [comment]
I've noted the slider does not change the status, but if you use the button (above the slider row) you can successfully toggle ID protection.

**Comment by CameronHall** [comment]
Unfortunately, there is no documentation from WHMCS on how this should function. It would appear to be another thing they've added in v8 but neglected to document.

As @xyzulu mentioned, you're best off using the buttons in the row above the sliders for now.
