### ISSUE TITLE
Error Transfering premium .co domain via WHMCS, but not Synergy Portal

### ISSUE THREAD

**Issue by myshophosting** [SynergyWholesale/WHMCS-Domains-Module#39]
When attempting to transfer a 'premium' .co domain from ENOM -> Synergy I got this error in WHMCS:

API Response:
Array
(
    [errorMessage] => Transfer Domain Failed - The provided domain name is premium and the premium acknowledgement flag was not provided
    [status] => ERR_TRANSFERDOMAIN_FAILED

I was subsequently able to start the transfer via the synergy portal, however, it should be doable via WHMCS.

**Comment by myshophosting** [comment]
Another domain - ending in .biz gave the same error.

**Comment by CameronHall** [comment]
Hi David,

I can see you already have a ticket with our team at the moment. This particular issue is related to a bug with our API which we've since fixed.

If you have any questions regarding this issue, our team will be happy to answer them via your support ticket.
