### ISSUE TITLE
Feature Request: WHMCS 7.10 - Registrar Price Sync

### ISSUE THREAD

**Issue by myshophosting** [SynergyWholesale/WHMCS-Domains-Module#4]
See: https://docs.whmcs.com/Version_7.10.0_Release_Notes

Specifically: Registrar TLD & Pricing Sync

This would be a great feature to add to this module. There are SO many domains now that being able to compare cost vs sell price would be very useful.

**Comment by CameronHall** [comment]
Hi @myshophosting,

I've implemented this in #5. WHMCS 7.10 is still in beta, so I'm going to hold off on publishing a release until it's stable. I have tested the new pricing sync feature against the latest version of WHMCS and it is working. I have found that the `setEppRequired` method isn't working and I've submitted a bug report to WHMCS.

I've attached a packaged version of #5 for you to try out if you're interested. 
[synergy-wholesale-domains-v2.1.0.zip](https://github.com/SynergyWholesale/WHMCS-Domains-Module/files/4341655/synergy-wholesale-domains-v2.1.0.zip)

**Comment by myshophosting** [comment]
Thanks- Will it work with the current version of WHMCS (minus the new sync feature of course) (i cant upgrade or dev the beta atm)

**Comment by CameronHall** [comment]
It should be fine, I've given it a brief test on 7.7 and it was developed against 7.10 and no issues so far.  I encourage you to make a backup of the module just in case you need to rollback.

**Comment by CameronHall** [comment]
I've created v2.1.0 as a formal pre-release. It can be found [here](https://github.com/SynergyWholesale/WHMCS-Domains-Module/releases/tag/v2.1.0).
