### ISSUE TITLE
Sync Redemption/Grace Fees not updating existing prices

### ISSUE THREAD

**Issue by JMOSSAU** [SynergyWholesale/WHMCS-Domains-Module#41]
Updated to v2.1.9 and re-ran the domain sync with Sync Redemption/Grace Fee set to ON, however old prices were not updated to the % set in the sync settings. Old prices that were manually entered remain. WHMCS 7.10.2

**Comment by CameronHall** [comment]
Hey @JMOSSAU,

Sorry for the delayed reply. For support you're best off lodging a ticket to get the best response times (< 1 hour). It's likely you missed the "Sync Redemption\Grace Fee" switch. 

![image](https://user-images.githubusercontent.com/7316093/97519341-3b6ee900-19ed-11eb-99b3-99ab39f217ff.png)

**Comment by JMOSSAU** [comment]
Hi @CameronHall,

As per my original post, switch was not missed. Switch was on everytime I tried it.

**Comment by CameronHall** [comment]
My mistake, I attempted to reproduce this today with no succeson WHMCS 8.0.2 so there is a possibility of this being an issue related to WHMCS 7. If you haven't already, please log a ticket and we can investigate further.
