### ISSUE TITLE
Issue with formatting on DNS management / URL forwarding page

### ISSUE THREAD

**Issue by oempire** [SynergyWholesale/WHMCS-Domains-Module#49]
Since updating to 8.1 We are having formatting issues on the DNS management / URL forward page within WHMCS as an end user

as you can see its quite broken - have tried latest module fro your site.

WHMCS advise that this appears to be from your plugin over riding the template

https://www.dropbox.com/s/7gkh81fyf23wrx2/2021-01-12_10-24-13.png?dl=0

**Comment by Sn0wCrack** [comment]
Hi @oempire,

We've now pushed out our new [v2.2.0 release](https://github.com/SynergyWholesale/WHMCS-Domains-Module/releases/tag/v2.2.0) which should resolve these issues you're facing.

To explain the issue it appears WHMCS' new Twenty One theme implemented Bootstrap 4, which broke some of our styling, as it relied on some Bootstrap 3 specific CSS classes, we've resolved this in such a way it should work with the WHMCS Six theme as well.

Please let us know if you continue to experience any issues with the new Twenty One theme in WHMCS 8.1.

**Comment by oempire** [comment]
thanks look like its working well now
